### ISSUE TITLE
Stash Api using .NET 4.0

### ISSUE THREAD

**Issue by sunkerGit** [jlouros/StashApiCSharp#15]
Hi,

I'm using VS 2012 with .NET 4.0, when installing nuget package (Install-Package Atlassian.Stash.Api -Version 1.0.15) i see the dependencies for Newtonsoft.Json (≥ 6.0.8) and Microsoft.AspNet.WebApi.Client (≥ 5.2.3) is using .NET framework 4.5. do you have backward compatible .NET framework stash api for .NET 4.0?

Cheers,
KS

**Comment by jlouros** [comment]
Hi @sunkerGit 

I can look into that.
I'm also adding a 'help wanted' if anyone wants to work on a solution for this issue.

**Comment by jlouros** [comment]
Fixed in version 3.0.0 https://www.nuget.org/packages/Atlassian.Stash.Api/3.0.0
