### ISSUE TITLE
Support for non root url's

### ISSUE THREAD

**Issue by dpan** [jlouros/StashApiCSharp#18]
The current implementation does not support url's like this one: scm.company.com/stash. It assumes all deployments are on the root of the domain (like scm.company.com)

In order for those url's to be supported you need to add a trailing slash in the base url and then remove the starting slash from the requestUrl.

I have hacked this to make it work but it's not pretty in the current design

**Comment by jlouros** [comment]
Fixed in version 3.0.0 https://www.nuget.org/packages/Atlassian.Stash.Api/3.0.0
