### ISSUE TITLE
Support for create tags

### ISSUE THREAD

**Issue by fixer-m** [jlouros/StashApiCSharp#22]
Hi.
Could you please add support for creating tags?
URL (post): rest/**git**/1.0/projects/{projectKey}/repos/{repositorySlug}/tags
https://developer.atlassian.com/static/rest/stash/3.11.3/stash-scm-git-rest.html

**Comment by jlouros** [comment]
The latest version [3.0.3](https://www.nuget.org/packages/Atlassian.Stash.Api/) now supports create and delete Tags

**Comment by fixer-m** [comment]
Thank you!
