### ISSUE TITLE
Bad request when getting file contents for a file in a subfolder

### ISSUE THREAD

**Issue by rogerbramon** [jlouros/StashApiCSharp#23]
When requesting Repositories.GetFileContents with a path of a file located in a subfolder it returns Bad Request. After inspecting it seems that the problem is related to the encoding of '/'. This is an example call returning bad request:
http://stashserverurl/rest/api/1.0/projects/my-project/repos/my-repo/browse/Build%2Fpackages.config

It works if %2F is replaced by /

**Comment by jlouros** [comment]
Fixing in version [3.0.5](https://www.nuget.org/packages/Atlassian.Stash.Api/3.0.5)
Good catch @rogerbramon 
Thanks for your help

**Comment by rogerbramon** [comment]
Thanks! It works perfect!
