### ISSUE TITLE
Support querying pullrequest comments

### ISSUE THREAD

**Issue by vijayshinva** [jlouros/StashApiCSharp#24]
Are there any plans to implement the comments API 

http://example.com/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/comments

**Comment by jlouros** [comment]
Hi @vijayshinva,

thanks for your suggestion. Supporting comments will take quite some time. I can work on that as soon as I have more availability. For now I will mark it "up-for-grabs".

**Comment by vijayshinva** [comment]
Thanks

**Comment by RSchwoerer** [comment]
Does this PR actually add comment functionality? I don't see it anywhere in the api, and there are not any examples in the integration test project.
