### ISSUE TITLE
Use the BitBucket Personal Access Token for authentication

### ISSUE THREAD

**Issue by mongeon** [jlouros/StashApiCSharp#39]
BitBucket users[ can create a personal token](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html) to authenticate themselves without providing their user/password. 

This is a scenario that we are willing to use. I've tried to modify the code for a pull request, but the constructors parameters of both StashClient and HttpCommunicationWorker are only string and conflict between Basic and Bearer authentication scenario. Any guidance on how you see doing it that you feel comfortable?

Thanks

**Comment by jlouros** [comment]
In order to be backwards compatible, I would add a new optional param to the constructor of `StashClient` defining the desired authentication method.

Something like:
```csharp
enum AuthMethod
{
    Basic,
    Bearer
}

public  StashClient(string baseUrl, string base64Auth = null, 
                    AuthMethod authMethod = AuthMethod.Basic) 
{ 
... 
}
```

If you see a better solution, feel free to add it.

**Comment by mongeon** [comment]
Good for me! I've also change the constructor of HttpCommunicationWorker to make it work. I've tested on my side and work fine. 

I'll try to create a pull request once I figure out how to go through the firewall at work, if not I will push it from home.

**Comment by RobertvBraam** [comment]
@jlouros I think this issues can be closed.
