### ISSUE TITLE
StashClient not available on .NET Core

### ISSUE THREAD

**Issue by ffMathy** [jlouros/StashApiCSharp#44]
Currently using .NET Core 2.0, and I can't find the `Atlassian.Stash` namespace. I can't find the `StashClient` either. It looks as if it isn't exposed properly.

**Comment by ffMathy** [comment]
Found some more details in the build log.

> warning MSB4078: The project file "src\Atlassian.Stash.NetCore\Atlassian.Stash.NetCore.csproj" is not supported by MSBuild and cannot be built.

**Comment by ffMathy** [comment]
Yes 😊

**Comment by ffMathy** [comment]
But note that that build log entry came from your build server, on the latest build.

**Comment by jlouros** [comment]
got it. At the moment I'm at work. I will spend some time investigating this issue once I get home.

**Comment by jlouros** [comment]
I was not able to find the build error. The last 2 builds were reported as successful: 

- https://ci.appveyor.com/project/jlouros/stashapicsharp/build/3.0.22
- https://ci.appveyor.com/project/jlouros/stashapicsharp/build/3.0.23

Can you share a link or a screenshot with the error?

**Comment by ffMathy** [comment]
It is right there in the last link you sent for `3.0.23`. Search for "NetCore" in your logs.
![image](https://user-images.githubusercontent.com/2824010/38563066-4dabe1d6-3cdc-11e8-8c7b-e845a08f9c0f.png)

**Comment by ffMathy** [comment]
@jlouros are you able to find it?

**Comment by ffMathy** [comment]
Also note that it does build successfully, but it still shows that warning and the nupkg file is empty and 0 bytes.

**Comment by jlouros** [comment]
I'm working adding Docker to be used for Integration testing. In that branch I'm doing to change the build script. Keep an eye on https://github.com/jlouros/StashApiCSharp/tree/docker

**Comment by ffMathy** [comment]
It has still not been resolved.

Here's a picture of the .NET Standard 2.0 version of the package after it is downloaded: 

![image](https://user-images.githubusercontent.com/2824010/38721416-649c5662-3efa-11e8-8c4b-6ed775eaef5c.png)

And here's the .NET 4.5 version:

![image](https://user-images.githubusercontent.com/2824010/38721425-75e3c1ee-3efa-11e8-8d57-c5aa2a448edd.png)

**Comment by ffMathy** [comment]
Did you verify that you are able to install the package from NET Core?

**Comment by jlouros** [comment]
yes I was able to by running the following commands:
```
dotnet new console -n stashClientCore
cd stashClientCore
dotnet add package Atlassian.Stash.Api --version 3.0.32
dotnet build
```

I'm using version 2.1.104 (output from `dotnet --version`)

**Comment by ffMathy** [comment]
Perfect! I just verified that it works too. Thanks for the effort!

Oh, and I just made another issue regarding updating pull requests.
