### ISSUE TITLE
Update pull requests

### ISSUE THREAD

**Issue by ffMathy** [jlouros/StashApiCSharp#48]
It doesn't seem to be possible to use the `PUT` variants for pull requests to update them. Is that correct?

**Comment by jlouros** [comment]
that is correct. `PUT` (update) is not correctly supported.
Related file: https://github.com/jlouros/StashApiCSharp/blob/master/src/Atlassian.Stash/Api/PullRequests.cs

**Comment by RobertvBraam** [comment]
This issue will be resolved in PR #64

**Comment by RobertvBraam** [comment]
@jlouros I think this issue can be closed right now, because it's now possible to update pullrequests

**Comment by jlouros** [comment]
yes, thanks @RobertvBraam 
as previously mentioned, this issue was resolved by #64
