### ISSUE TITLE
Add Support for the Path Parameter in Repository.GetFiles()

### ISSUE THREAD

**Issue by brifly** [jlouros/StashApiCSharp#51]
Repository.GetFiles() currently gets a list of all files in the repo, the rest API supports a path parameter that lets you get files in a sub-directory.

**Comment by brifly** [comment]
I've implemented this locally - @jlouros if you add me as a contributor I can create a pull request.

**Comment by jlouros** [comment]
implemented in https://github.com/jlouros/StashApiCSharp/pull/52
