### ISSUE TITLE
Improper instantiation of HttpClient 

### ISSUE THREAD

**Issue by RobertvBraam** [jlouros/StashApiCSharp#65]
The HttpCommunicationWorker makes a new instance of the HttpClient every request. This is a bad practice, because it's intended to live for a longer and preferably reused for every request. @jlouros I would like to fix it, but I thought first run it through you to agree on this problem.

Sources:
https://blogs.msdn.microsoft.com/shacorn/2016/10/21/best-practices-for-using-httpclient-on-services/
https://docs.microsoft.com/en-us/azure/architecture/antipatterns/improper-instantiation/

**Comment by jlouros** [comment]
I also read it on https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ a while ago but I never came back to this project to fix it.

I totally agree this should be fixed.
